version: 2
jobs:
  build:
    working_directory: ~/cci-filmratings
    docker:
      - image: circleci/clojure:lein-2.8.1
      environment:
        LEIN_ROOT: nbd
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore cache:
            key: film-rating-{{ checksum "project.clj" }}
        - run: lein do test, uberjar
              
